- set_fact: realm={{ realm_template.content | regex_replace('userx', item) }}

- name: Delete {{ item }} Realm
  uri: 
    url: 'https://sso-{{sso_project}}.{{ocp_apps_domain}}/auth/admin/realms/{{item}}'
    method: DELETE
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer {{ TKN }}"
    validate_certs: no
  failed_when: false
