---
- name: Get SSO token
  shell: "curl --insecure -X POST 'https://sso-{{sso_project}}.{{ocp_apps_domain}}/auth/realms/master/protocol/openid-connect/token' \
  -H 'Content-Type: application/x-www-form-urlencoded' -d 'username={{ eval_rhsso_admin_username | default('keyadmin') }}' -d 'password={{ eval_rhsso_admin_password | default('keypassword') }}' -d 'grant_type=password' -d 'client_id=admin-cli'"
  register: token_text

- set_fact: TKN={{ (token_text.stdout | from_json).access_token }}

- name: Get realm template
  uri:
    url: 'https://raw.githubusercontent.com/jbossdemocentral/3scale-api-workshop/master/support/templates/realm-template.json'
    return_content: yes
  register: realm_template

- name: Delete SSO user realms
  include_tasks: ./delete-realm.yml
  with_sequence: start=1 end={{ usersno }} format=user%d
  when: delete_realms

- name: Create SSO threescale realm
  include_tasks: ./delete-realm.yml
  vars:
    item: threescale
  when: delete_realms

- name: Create SSO Microcks realm
  include_tasks: ./delete-realm.yml
  vars:
    item: microcks
  when: delete_realms

- name: Create SSO Apicurio realm
  include_tasks: ./delete-realm.yml
  vars:
    item: apicurio
  when: delete_realms

- name: Delete service
  shell: "oc delete service http -n {{ sso_project }}"
  register: output
  failed_when: output.stderr != '' and 'not found' not in output.stderr

- name: Delete service
  shell: "oc delete route http -n {{ sso_project }}"
  register: output
  failed_when: output.stderr != '' and 'not found' not in output.stderr